# The identifier regular expression
identifierRegEx: "%LORE%"

lores:
  test:
    lore:
    - "&6| 33&r"
    - "&6| Yea&r"
    weight: 0.6
  another:
    lore:
    - "&c< Also 33&r"
    - "&c< Also 33&r"
    weight: 0.3
  another2:
    lore:
    - "&a> 33&r"
    - "&a> 33&r"
    weight: 0.1